name: sleepPy_environment

channels:
        - defaults
        - conda-forge

dependencies:
- python == 3.7
- python.app
- numpy == 1.15
- pandas == 0.23.3
- matplotlib == 3.0.2
- seaborn == 0.9.0
- ipykernel == 5.1.0
- pingouin == 0.2.3
- pyqt == 5.9.2
- astropy == 3.1
- pip
- pip:
  - git+https://github.com/A-Fisk/sleepPy.git@master
  - git+https://github.com/A-Fisk/actiPy.git@master
